import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/src/components/Molecoles/Header/Header";
import WindowBox from "@/src/components/Organism/WindowBox";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>AI Story Teller</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<Header title="AI Story Teller" />
				<div className={styles.content}>
					<WindowBox title="Story Params" />
				</div>
			</main>
		</>
	);
}
